# Sample using Ceph as a glance backend
# Requires a running cinder volume service
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  serviceUser: glance
  containerImage: quay.io/podified-antelope-centos9/openstack-glance-api:current-podified
  customServiceConfig: |
    [DEFAULT]
    enabled_backends = default_backend:cinder
    [glance_store]
    default_backend = default_backend
    [default_backend]
    rootwrap_config = /etc/glance/rootwrap.conf
    description = Default cinder backend
    cinder_catalog_info = volumev3::publicURL
  customServiceConfigSecrets:
    - osp-glance-cinder-secret
  databaseInstance: openstack
  databaseUser: glance
  glanceAPIInternal:
    debug:
      service: false
    preserveJobs: false
    replicas: 1
  glanceAPIExternal:
    debug:
      service: false
    preserveJobs: false
    replicas: 1
  secret: osp-secret
  storageClass: ""
  storageRequest: 1G
